kind: pipeline
name: drone-portainer

steps:
  - name: build
    image: plugins/docker
    settings:
      repo: dkr.salcedo.tech/drone-portainer
      registry: dkr.salcedo.tech
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
