kind: pipeline
type: docker
name: drone-portainer

steps:
# 构建代码 docker 镜像
-   name: build
    image: plugins/docker
    settings:
      repo: 192.168.50.252:65000/allanpk716/drone-portainer
      storage_driver: vfs    #出错原因就是它
      registry: 192.168.50.252:65000
      insecure: true         #私有仓库未设置HTTPS需要启用这个选项
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
      tags:
        - latest
# Bark 通知
-   name: Bark Notify
    image: byrnedo/alpine-curl
    environment:
        barkfront:
            from_secret: bark_front
        droneweb: 
            from_secret: drone_web
    commands:
    - curl "$barkfront/${DRONE_REPO_NAME}?url=$droneweb/${DRONE_REPO}/${DRONE_BUILD_NUMBER}"
    when:
        status:
        - success
        - failure